services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    expose:
      - "8000:8000"
    networks:
      - app-network

  db:
    build:
      context: ./database
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
